// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/list/{id}": {
            "get": {
                "security": [
                    {
                        "X-API-Key": []
                    }
                ],
                "description": "Show all app list of apk and aab",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "File"
                ],
                "summary": "Show file from user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/utils.Showfile"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.BadRequest"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.InternalServerError"
                        }
                    }
                }
            }
        },
        "/api/v1/upload/{username}": {
            "post": {
                "security": [
                    {
                        "X-API-Key": []
                    }
                ],
                "description": "Upload file based on user id or username",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "File"
                ],
                "summary": "Upload file apk or aab",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.RequestInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/utils.Success"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.BadRequest"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.InternalServerError"
                        }
                    }
                }
            }
        },
        "/api/v1/{id}": {
            "delete": {
                "security": [
                    {
                        "X-API-Key": []
                    }
                ],
                "description": "Delete user file based on username",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "File"
                ],
                "summary": "Delete all file apk or aab and user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/utils.Success"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.BadRequest"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.InternalServerError"
                        }
                    }
                }
            }
        },
        "/api/v1/{id}/{hash}": {
            "delete": {
                "security": [
                    {
                        "X-API-Key": []
                    }
                ],
                "description": "Delete file based on user id or username using hash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "File"
                ],
                "summary": "Delete file apk or aab",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "hash",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/utils.Success"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.BadRequest"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.InternalServerError"
                        }
                    }
                }
            }
        },
        "/getfile/{id}/{hash}": {
            "get": {
                "description": "Download file using username and hash when getting from list apk",
                "tags": [
                    "File"
                ],
                "summary": "Download file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "hash",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "api.RequestInput": {
            "type": "object",
            "required": [
                "file",
                "id",
                "label_name",
                "version_app"
            ],
            "properties": {
                "file": {
                    "type": "string",
                    "example": "file.aab"
                },
                "id": {
                    "type": "string",
                    "example": "id.co.example.username"
                },
                "label_name": {
                    "type": "string",
                    "example": "Example Apps"
                },
                "version_app": {
                    "type": "string",
                    "example": "v1.0.0"
                }
            }
        },
        "utils.BadRequest": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "string"
                },
                "message": {
                    "type": "string",
                    "example": "message"
                },
                "result": {
                    "type": "string",
                    "example": "null"
                },
                "status": {
                    "type": "integer",
                    "example": 400
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "utils.InternalServerError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "message"
                },
                "message": {
                    "type": "string",
                    "example": "message"
                },
                "result": {
                    "type": "string",
                    "example": "null"
                },
                "status": {
                    "type": "integer",
                    "example": 500
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "utils.Showfile": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "null"
                },
                "message": {
                    "type": "string",
                    "example": "message"
                },
                "result": {
                    "type": "object",
                    "properties": {
                        "aab": {
                            "type": "object",
                            "properties": {
                                "hash.aab": {
                                    "type": "object",
                                    "properties": {
                                        "filename": {
                                            "type": "string",
                                            "example": "file.aab"
                                        },
                                        "index": {
                                            "type": "integer",
                                            "example": 1
                                        },
                                        "package_name": {
                                            "type": "string",
                                            "example": "id.co.example.username"
                                        },
                                        "upload_at": {
                                            "type": "string",
                                            "example": "2025-01-27T22:40:37.773666331+07:00"
                                        },
                                        "url": {
                                            "type": "string",
                                            "example": "/username/hash"
                                        }
                                    }
                                }
                            }
                        },
                        "apk": {
                            "type": "object",
                            "properties": {
                                "hash.apk": {
                                    "type": "object",
                                    "properties": {
                                        "filename": {
                                            "type": "string",
                                            "example": "file.apk"
                                        },
                                        "index": {
                                            "type": "integer",
                                            "example": 1
                                        },
                                        "package_name": {
                                            "type": "string",
                                            "example": "id.co.example.username"
                                        },
                                        "upload_at": {
                                            "type": "string",
                                            "example": "2025-01-27T19:44:25.467738468+07:00"
                                        },
                                        "url": {
                                            "type": "string",
                                            "example": "/username/hash"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "status": {
                    "type": "integer",
                    "example": 200
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "utils.Success": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "null"
                },
                "message": {
                    "type": "string",
                    "example": "message"
                },
                "result": {
                    "type": "string",
                    "example": "message"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        }
    },
    "securityDefinitions": {
        "X-API-Key": {
            "description": "Input your token authorized",
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Filestore",
	Description:      "Documentation for Filestore",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
